Microsoft Windows [Version 10.0.19045.2486]
(c) Microsoft Corporation. All rights reserved.

C:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes>activate

(base) C:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes>conda activate 
c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\.conda

(c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\.conda) C:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes>c:/Users/loniw/OneDrive/Documents/School/WebStreaming/streaming-02-multiple-processes/.conda/python.exe c:/Users/loniw/OneDrive/Documents/School/WebStreaming/streaming-02-multiple-processes/multiple_processes.py


STARTING UP.............................
It's 2023-01-15 at 06:07 PM

This file is running on:    nt Windows 10
The Python version is:      3.10.8

The Python interpreter is at:
 c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\.conda\python.exe


DELETED tabble pets.
CREATED table pets.

P1 getting ready to insert Ace the Dog.
P1 ADDED Ace the Dog.
P2 getting ready to insert Cooper the Rabbit.
P3 getting ready to insert Emma the Rabbit.
P1 getting ready to insert Buddy the Dog.
P1 ADDED Buddy the Dog.
Process Process-2:
Process Process-3:
Traceback (most recent call last):
  File "c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\.conda\lib\multiprocessing\process.py", line 
314, in _bootstrap
    self.run()
  File "c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\.conda\lib\multiprocessing\process.py", line 
108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\multiple_processes.py", line 106, in process_two
    insert_pet("P2", "Cooper", "Rabbit")
  File "c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked
Traceback (most recent call last):
  File "c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\.conda\lib\multiprocessing\process.py", line 
314, in _bootstrap
    self.run()
  File "c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\.conda\lib\multiprocessing\process.py", line 
108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\multiple_processes.py", line 110, in process_three
    insert_pet("P3","Emma", "Rabbit")
  File "c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked

(c:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes\.conda) C:\Users\loniw\OneDrive\Documents\School\WebStreaming\streaming-02-multiple-processes>